version: 1.0.{build}
branches:
  only:
  - development    # build the default branch
  - /^release-.+/  # build release branches
  - /^Mudlet-.+/   # build release tags (yes, the option also applies to tags)
init:
- cmd: mkdir C:\src\
image: Visual Studio 2019
environment:
  signing_password:
    secure: gOKqBtIvfDuGkEeaHGaguMmafynYAG06iVuD6Krem7M=
  DEPLOY_KEY_PASS:
    secure: 81sr0SJzuWG+mgH3X6fJTh4rfX5/O1qa3MsItNvFukQ=
  DEPLOY_PATH:
    secure: XQhASAJJm4Owpu74K4jgL0gszN59XJnCAS27NG7CW5G1LSRSWRh/EhKiTD36DvSr
  DBLSQD_USER:
    secure: MzfNcBLZRfswzBQufoW4EV+9/tcG5vW+G6EVTyN6Glc=
  DBLSQD_PASS:
    secure: Bm5PLJjC39XmRC55RPGVP9c5CFxvWu2VorAAmu5QS38=
  matrix:
  - QT_BASE_DIR: C:\Qt\5.13.2\mingw73_32
    MINGW_BASE_DIR: C:\Qt\Tools\mingw730_32
install:
- cd "%APPVEYOR_BUILD_FOLDER%\CI"
- ps: |

    Set-Content -Path 'C:\Qt\5.13.2\mingw73_32\mkspecs\qconfig.pri' -Value 'QT_ARCH = i386
    QT_BUILDABI = i386-little_endian-ilp32
    QT.global.enabled_features = shared debug_and_release build_all c++11 c++14 c++1z c99 c11 thread future concurrent
    QT.global.disabled_features = cross_compile framework rpath appstore-compliant c++2a pkg-config force_asserts separate_debug_info simulator_and_device static
    QT_CONFIG += shared debug_and_release debug release build_all c++11 c++14 c++1z concurrent dbus no-pkg-config stl
    CONFIG += shared release no_plugin_manifest
    QT_VERSION = 5.13.2
    QT_MAJOR_VERSION = 5
    QT_MINOR_VERSION = 13
    QT_PATCH_VERSION = 2
    QT_GCC_MAJOR_VERSION = 7
    QT_GCC_MINOR_VERSION = 3
    QT_GCC_PATCH_VERSION = 0
    QT_EDITION = OpenSource
    QT_LICHECK =
    QT_RELEASE_DATE = 2019-10-28'
    
    Set-Content -Path 'C:\Qt\5.13.2\mingw73_32\bin\qt.conf' -Value '[Paths]
    Documentation=../../Docs/Qt-5.13.2
    Examples=../../Examples/Qt-5.13.2
    Prefix=..'

    Set-Content -Path 'C:\Qt\5.13.2\mingw73_32\bin\qtenv2.bat' -Value '@echo off
    echo Setting up environment for Qt usage...
    set PATH=C:\Qt\5.13.2\mingw73_32\bin;C:/Qt/Tools/mingw730_32\bin;%PATH%
    cd /D C:\Qt\5.13.2\mingw73_32'
- powershell ".\appveyor.install.ps1"

build_script:
- cd "%APPVEYOR_BUILD_FOLDER%\CI"
- powershell ".\appveyor.build.ps1"

on_failure:
- cd C:\src
- bash -c "curl --upload-file ./verbose_output.log https://transfer.sh/verbose_output.log"

cache:
  - '%MINGW_BASE_DIR% -> CI\appveyor.install.ps1, CI\appveyor.functions.ps1'

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/2d6f7bea328a9dd60769
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
  body: >-
    {
      "message": "Appveyor {{repositoryName}}{{#isPullRequest}}#{{pullRequestId}}{{/isPullRequest}}{{^isPullRequest}} ({{branch}}){{/isPullRequest}} {{#passed}}passed{{/passed}}{{#failed}}failed{{/failed}} ({{buildNumber}})",
      "level": "{{#passed}}info{{/passed}}{{#failed}}error{{/failed}}"
    }
